- Defective cooling, mice infestation and mold—severe hygiene breaches
- Massive cleanliness failures exposed in undercover reports
- Ignoring human-rights and labor violations in supplier plantations
- underpaid labor and unsafe conditions
- Environmental destruction and rights abuses on palm-oil plantations
- Misleading use of RSPO eco-label despite rights and environmental breaches
- metal fragments found in packaged food
- Illegal internal surveillance and “spy” operations against employees
- Poor transparency, labor and womens rights violations, neglect of small-scale producers
- Intransparent discount schemes—special app-only prices not clearly disclosed
- Excessive single-use packaging and lack of reuse options
-  discounts shown without final prices
- Raised minimum-spend thresholds for coupon redemption, disadvantaging shoppers
- Charging customers for the weight of packaging (bag weight passed onto buyer)
- Bonus-app only displays discount amounts, not original prices—considered deceptive
- unauthorized collection of employee medical and personal data
- Secret price-fixing agreements leading to hefty fines
- anticompetitive retaliation via antitrust complaints
- Overuse of single-use plastics despite sustainability pledges
- Investigations into possible price-collusion among discounters
- High rates of plastic packaging in produce aisles
- Collusion among potato processors to fix prices, hurting consumers
- Expired food sold to customers
- Mislabeling of product origin or ingredients
- Unlawful destruction of unsold food
- Racial profiling or discrimination against customers or staff
- Wage theft or forced unpaid overtime
- Unlawful dismissal or retaliation against whistleblowers
- Unlawful surveillance of customers
- Excessive use of security guards or aggressive staff conduct
- Misleading “organic” or “sustainable” labeling
- Non-compliance with accessibility requirements
- Unlawful restriction of labor union activities
- Unreported workplace injuries or safety violations
- Disposal of hazardous materials without compliance
- Discrimination in promotions or pay
- Failure to recall unsafe products
- Improper disposal of e-waste or batteries
- Greenwashing—false environmental claims
- Child labor or forced labor in supply chains
- Animal cruelty or lack of animal welfare standards
- Unjustified refusal of returns or complaints
- Unreasonable delays in refunds or compensation
- Aggressive upselling or pressure tactics
- Unjustified store bans or trespass orders
- Lack of transparency in pricing or promotions
- Food donations blocked or destroyed instead of being given to charity
- Lack of allergy warnings or mislabeling allergens
- Unhygienic restroom or staff facilities
- Improper temperature controls for perishables
- Unfair treatment of part-time or temporary staff
- Price manipulation during emergencies or crises
- Refusal to accept cash or discrimination against unbanked customers
- Hidden fees or surcharges at checkout
- Predatory lending or high-interest payment plans for purchases
- Misuse of customer data for marketing without consent
- Obstruction of investigative journalists or activists
- Physical intimidation of protestors or labor organizers
- Unlawful facial recognition or biometric surveillance
- Deceptive shrinkflation (reducing package size without lowering price)
- Fake reviews or paid review manipulation
- Unexplained stock shortages or “phantom” promotions
- Stale bread or spoiled bakery goods being resold
